-- MySQL Script generated by MySQL Workbench
-- Tue Dec  7 18:55:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JavaFxdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JavaFxdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JavaFxdb` DEFAULT CHARACTER SET utf8 ;
USE `JavaFxdb` ;

-- -----------------------------------------------------
-- Table `JavaFxdb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaFxdb`.`Students` (
  `StudentId` INT NOT NULL AUTO_INCREMENT,
  `StudentName` VARCHAR(45) NOT NULL,
  `StudentSurname` VARCHAR(45) NOT NULL,
  `StudentCourse` INT NOT NULL,
  `StudentGroup` VARCHAR(45) NOT NULL,
  `StudentsGender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StudentId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
